apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: ctse-api_gateway
        image: priyanthafer/ctse-api_gateway:latest
        ports:
        - containerPort: 5001
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
