name: Dependency Audit

on:
  pull_request:
    branches:
      - main

jobs:
  audit:
    strategy:
      matrix:
        service: [api-gateway, logistics, user]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: logistics-api-gateway/${{ matrix.service }}

      - name: Run dependency audit
        run: npm audit
        working-directory: logistics-api-gateway/${{ matrix.service }}
