name: Dependency Audit

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  audit:
    strategy:
      matrix:
        service: [api-gateway, logistics, user]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: logistics-api-gateway/${{ matrix.service }}
        run: npm install

      - name: Run dependency audit
        working-directory: logistics-api-gateway/${{ matrix.service }}
        run: npm audit